export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const FAVORITES_ROUTE = '/favorites'
export const AUTO_ROUTE = '/auto'